CREATE TABLE `merchant_account` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `company_id` bigint(20) DEFAULT NULL,
  `profile_id` varchar(45) DEFAULT NULL,
  `dba_name` varchar(100) DEFAULT NULL,
  `mid` varchar(50) DEFAULT NULL,
  `discover_mid` varchar(50) DEFAULT NULL,
  `internal_mid` varchar(50) DEFAULT NULL,
  `eftex_mid` varchar(50) DEFAULT NULL,
  `alipay_id` varchar(100) DEFAULT NULL,
  `portfolio_id` int(11) DEFAULT NULL,
  `open_date` date DEFAULT NULL,
  `close_date` date DEFAULT NULL,
  `descriptor` text,
  `creation_date` datetime DEFAULT NULL,
  `legal_name` varchar(100) DEFAULT NULL,
  `is_legal_entity` bit(1) DEFAULT NULL,
  `mcc_code_id` int(11) DEFAULT NULL,
  `merchant_type_id` int(11) DEFAULT NULL,
  `business_type_id` int(11) DEFAULT NULL,
  `created_by` bigint(20) DEFAULT NULL,
  `updation_date` datetime DEFAULT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  `status_id` int(11) DEFAULT NULL,
  `processor_id` int(11) DEFAULT NULL,
  `acquirer_id` int(11) DEFAULT NULL,
  `parent_id` bigint(20) DEFAULT NULL,
  `hierarchy_type` int(11) DEFAULT NULL,
  `settlement_level` int(11) DEFAULT NULL,
  `statement_level` int(11) DEFAULT NULL,
  `section_ids` varchar(100) DEFAULT NULL,
  `merchant_detail_info` json DEFAULT NULL,
  `is_TPP` bit(1) DEFAULT NULL,
  `unique_id` bigint(20) DEFAULT NULL,
  `soft_descriptor` varchar(50) DEFAULT NULL,
  `settlement_method_id` int(11) DEFAULT NULL,
  `business_boarded_date` datetime DEFAULT NULL,
  `additional_equipment_details` json DEFAULT NULL,
  `is_data_migration_done` bit(1) DEFAULT NULL,
  `original_merchant_detail_info` json DEFAULT NULL,
  `risk_monitored` bit(1) DEFAULT b'0',
  `funding_cycle` int(11) DEFAULT NULL,
  `suggested_rep_code` varchar(20) DEFAULT NULL,
  `lead_source_id` bigint(20) DEFAULT NULL,
  `risk_category_id` int(11) DEFAULT NULL,
  `scoring_template_id` bigint(20) DEFAULT NULL,
  `funding_level_id` int(11) DEFAULT NULL,
  `sales_office_name` varchar(200) DEFAULT NULL,
  `agent_contact_name` varchar(100) DEFAULT NULL,
  `agent_contact_email` varchar(100) DEFAULT NULL,
  `assigned_to` bigint(20) DEFAULT NULL,
  `direct_debit` bit(1) DEFAULT NULL,
  `risk_processing_info` json DEFAULT NULL,
  `partner_id` varchar(250) DEFAULT NULL,
  `acquiring_bank_id` int(11) DEFAULT NULL,
  `boarding_info` json DEFAULT NULL,
  `servicing_tech` json DEFAULT NULL,
  `servicing_other` json DEFAULT NULL,
  `is_welcome_kit_sent` bit(1) DEFAULT NULL,
  `merchant_partner_id` bigint(20) DEFAULT NULL,
  `sponsor_bank_id` bigint(20) DEFAULT NULL,
  `funding_time` int(11) DEFAULT NULL,
  `fee_transfer_model` int(11) DEFAULT NULL,
  `un_pended` bit(1) DEFAULT NULL,
  `import_file_log_id` bigint(20) DEFAULT NULL,
  `additional_pricing_info` json DEFAULT NULL,
  `merchant_import_ids` text,
  `code` varchar(50) DEFAULT NULL,
  `is_full_uw_approval` bit(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_merchant_portfolio_id` (`portfolio_id`),
  KEY `fk_merchant_account_created_by_idx` (`created_by`),
  KEY `fk_merchant_account_updated_by_idx` (`updated_by`),
  KEY `fk_mer_acc_mcc_code_id_idx` (`mcc_code_id`),
  KEY `fk_mer_acc_merchant_type_id_idx` (`merchant_type_id`),
  KEY `fk_mer_acc_business_type_id_idx` (`business_type_id`),
  KEY `fk_mer_acc_status_id_idx` (`status_id`),
  KEY `fk_mer_acc_processorid` (`processor_id`),
  KEY `fk_mer_acc_acquirerid` (`acquirer_id`),
  KEY `fk_mer_acc_mid_c_id` (`mid`,`company_id`),
  KEY `fk_mer_acc_settlement_method_id` (`settlement_method_id`),
  KEY `merchant_account_idx_processor_id_id` (`processor_id`,`id`),
  KEY `fk_merchant_account_funding_cycle` (`funding_cycle`),
  KEY `fk_mer_acc_risk_category_id` (`risk_category_id`),
  KEY `fk_mer_acc_scoring_template_id` (`scoring_template_id`),
  KEY `fk_mer_acc_funding_level_id` (`funding_level_id`),
  KEY `fk_merchant_assigned_to` (`assigned_to`),
  KEY `fk_ma_funding_time` (`funding_time`),
  KEY `fk_ma_fee_transfer_model` (`fee_transfer_model`),
  KEY `fk_mer_acc_merchant_partner_id` (`merchant_partner_id`),
  CONSTRAINT `fk_ma_fee_transfer_model` FOREIGN KEY (`fee_transfer_model`) REFERENCES `entity_type_master` (`id`),
  CONSTRAINT `fk_ma_funding_time` FOREIGN KEY (`funding_time`) REFERENCES `entity_type_master` (`id`),
  CONSTRAINT `fk_mer_acc_acquirerid` FOREIGN KEY (`acquirer_id`) REFERENCES `acquiring_entity` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_business_type_id` FOREIGN KEY (`business_type_id`) REFERENCES `entity_type_master` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_funding_level_id` FOREIGN KEY (`funding_level_id`) REFERENCES `entity_type_master` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_mcc_code_id` FOREIGN KEY (`mcc_code_id`) REFERENCES `entity_type_master` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_merchant_partner_id` FOREIGN KEY (`merchant_partner_id`) REFERENCES `partner_account` (`id`),
  CONSTRAINT `fk_mer_acc_merchant_type_id` FOREIGN KEY (`merchant_type_id`) REFERENCES `entity_type_master` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_processorid` FOREIGN KEY (`processor_id`) REFERENCES `acquiring_entity` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_risk_category_id` FOREIGN KEY (`risk_category_id`) REFERENCES `entity_type_master` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_scoring_template_id` FOREIGN KEY (`scoring_template_id`) REFERENCES `uw_scoring_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_settlement_method_id` FOREIGN KEY (`settlement_method_id`) REFERENCES `entity_type_master` (`id`),
  CONSTRAINT `fk_mer_acc_status_id` FOREIGN KEY (`status_id`) REFERENCES `entity_type_master` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mer_acc_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_merchant_account_funding_cycle` FOREIGN KEY (`funding_cycle`) REFERENCES `entity_type_master` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_merchant_account_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_merchant_assigned_to` FOREIGN KEY (`assigned_to`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_merchant_portfolio_id` FOREIGN KEY (`portfolio_id`) REFERENCES `residual_plan` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=170978 DEFAULT CHARSET=latin1;